apiVersion: v1
kind: ConfigMap
metadata:
  name: afrilumina-config
data:
  SPRING_PROFILES_ACTIVE: "prod"
  DB_PORT: "3306"
  DB_NAME: "afrilumina"
  PAYPAL_BASE_URL: "https://api-m.sandbox.paypal.com"   # change to live URL when going live
  ALLOWED_ORIGINS: "https://www.afriluminahub.com"
  ADMIN_SEED_NAME: "Reagan"
  MPESA_SHORT_CODE: "REPLACE_WITH_SHORTCODE"        # e.g. 174379 for sandbox
  MPESA_API_URL: "https://sandbox.safaricom.co.ke"  # switch to https://api.safaricom.co.ke in prod
  MPESA_CALLBACK_URL: "https://www.afriluminahub.com/api/mpesa/callback"